// Vocabulary for Halloween Costume Idea Generator

// define adjectives - Modifier for the character
var adj = [
  "8-foot tall",
  "<small>LEGO</small>",
  "Amnesiac",
  "Baby",
  "Bald",
  "Blonde",
  "Brain-damaged",
  "Bug-eyed",
  "Cannibal",
  "Clumsy",
  "Constipated",
  "Cross-eyed",
  "Disco",
  "Disoriented",
  "Drooling",
  "Drunk",
  "Frozen",
  "Handcuffed",
  "Hobo",
  "Hunchback",
  "Hungover",
  "Hyperventilating",
  "Incontinent",
  "Mechanical",
  "Heavy Metal",
  "Nearsighted",
  "Overweight",
  "Redhead",
  "Robot",
  "Sexy",
  "Shrunken",
  "Sleep-walking",
  "Slime-covered",
  "Spastic",
  "Stinky",
  "Stuttering",
  "Undead",
  "Unemployed",
  "Wooden",
  "Yodelling"
];

// define objects - the basic character the costume is based on
var obj = [
  "Abraham Lincoln",
  "ALF",
  "Alien",
  "Alligator",
  "Amoeba",
  "Anglerfish",
  "Anime Princess",
  "Bart Simpson",
  "Batman &amp; Robin",
  "Bumblebee",
  "Ben Franklin",
  "Bernie Sanders",
  "Biff Tannen",
  "Big Bird",
  "Bilbo",
  "Bowser",
  "Burger King",
  "C3PO",
  "Captain Kirk",
  "Captain Picard",
  "Catwoman",
  "Centaur",
  "Cheerleader",
  "Chewbacca",
  "Chicken",
  "Chuck Norris",
  "Clown",
  "Construction Worker",
  "Count",
  "Cujo",
  "Cylon",
  "Dalek",
  "Darth Maul",
  "Darth Vader",
  "Dementor",
  "Disembodied Head",
  "Doc Brown",
  "Dog Catcher",
  "Dolphin",
  "Donald Trump"
  "Dr. Evil",
  "Dr. Who",
  "Dracula",
  "Dumbledore",
  "E.T.",
  "Easter Bunny",
  "Eiffel Tower",
  "Elf",
  "Elmo",
  "Empire State Building",
  "Exorcist",
  "Fairy",
  "Flash",
  "Frankenstein",
  "Freddy Kruger",
  "Frenchman",
  "Frodo",
  "Galdalf",
  "Garfield",
  "George Washington",
  "Ghost",
  "Gimli",
  "Goblin",
  "Godzilla",
  "Grim Reaper",
  "Grinch",
  "Hamster",
  "Harry Potter",
  "Headless Horseman",
  "Hermione",
  "Hillary Clinton",
  "Hobbit",
  "Homer Simpson",
  "Hulk",
  "Hyena",
  "Indiana Jones",
  "Inigo Montoya",
  "James Bond",
  "Jason",
  "Joe Camel",
  "Joker",
  "Kermit",
  "Khaddafi",
  "King Arthur",
  "King Kong",
  "Klingon",
  "Legolas",
  "Leprechaun",
  "Lex Luthor",
  "Lois Lane",
  "Luigi",
  "Mannequin",
  "Mario",
  "Mayor McCheese",
  "Medieval Knight",
  "Menudo",
  "Michael Jackson",
  "Minion",
  "Monkey",
  "Mormon Tabernacle Choir",
  "Mr Rogers",
  "Mr. Spock",
  "Mummy",
  "Napoleon",
  "Ogre",
  "Optimus Prime",
  "Orangutan",
  "Palpatine",
  "Peewee Herman",
  "Peter Pan",
  "Penguin",
  "Pikachu",
  "Pirate",
  "Platypus",
  "Policeman",
  "Popeye",
  "Porcupine",
  "Priest",
  "Princess Leia",
  "Princess Peach",
  "R2D2",
  "Sailor",
  "Sandman",
  "Santa",
  "Satan",
  "Sauron",
  "Sir Lancelot",
  "Skeleton",
  "Smurf",
  "Spiderman",
  "Squirrel",
  "Stormtrooper",
  "Sumo Wrestler",
  "Superman",
  "Surgeon",
  "Terminator",
  "Three Stooges",
  "Tony the Tiger",
  "Tooth Fairy",
  "Vampire",
  "Voldemort",
  "Werewolf",
  "Wicked Witch",
  "Wonder Woman",
  "Yeti",
  "Yoda",
  "Yogi Bear",
  "Zebra",
  "Zombie",
  "Zorro"
];

// define state1 - conditions, dispositions, or things they have with them:
var state1 = [
  "breakdancing",
  "eating a burrito",
  "eating a turkey leg",
  "hitting on everyone",
  "in a bikini",
  "in a body cast",
  "in a cowboy hat",
  "in a diving outfit",
  "in a kilt",
  "in a skirt",
  "in a phone booth",
  "in a pith helmet",
  "in a propellor beanie",
  "in a spacesuit",
  "in a Tardis",
  "in a tornado",
  "in a tutu",
  "in a tuque",
  "in a tuxedo",
  "in a viking helmet",
  "in a zoot suit",
  "in lederhosen",
  "in pumps",
  "on a scooter",
  "on a skateboard",
  "on a tricycle",
  "on a unicycle",
  "on fire",
  "on skis",
  "playing a banjo",
  "playing the accordion",
  "playing the bouzouki",
  "playing the harmonica",
  "playing the triangle",
  "with a black eye",
  "with a dickie",
  "with a lisp",
  "with a monocle",
  "with a pegleg",
  "with a scarf",
  "with a tiny head",
  "with an afro",
  "with an arrow through the head",
  "with antlers",
  "with braces",
  "with bunny ears",
  "with eight arms",
  "with goggles",
  "with googley eyes",
  "with fangs",
  "with no pants",
  "with no short-term memory",
  "with tentacles",
  "with terrible acne",
  "with Tourette's",
  "with two heads"
];

// define state2 - things that can substitute for body parts
// (first item blank)
var state2 = [
  "a baseball bat",
  "a basketball hoop",
  "a beer keg",
  "a blowtorch",
  "a bong",
  "a boomerang",
  "a bottle of whiskey",
  "a chainsaw",
  "a cigar",
  "a goatee",
  "a hook",
  "a hoola hoop",
  "a lawn mower",
  "a megaphone",
  "a mohawk",
  "a pineapple",
  "a pizza box",
  "a rubber duck",
  "a scythe",
  "a tennis racket",
  "a trebuchet",
  "an axe",
  "an eggbeater",
  "hedge-clippers",
  "muttonchops"
];

// define substitution - body part to be substituted
var subst = [
  "for a foot",
  "for a hand",
  "for a head",
  "for a nose"
];



